### ISSUE TITLE
wrong guide in `juejin -h`

### ISSUE THREAD

**Issue by tonghuashuo** [cheng2xin/juejin#1]
OS: macOS High Sierra 10.13.2
node: 9.3.0
npm 5.6.0

I just installed juejin the cli tool. but no command worked so far. (details in picture)

<img width="640" alt="juejin" src="https://user-images.githubusercontent.com/6594276/35044741-75cf4c62-fbcc-11e7-8f2e-f9485ec35d26.png">

Then I took a look back to the [article](https://juejin.im/post/5a5f18246fb9a01cb42c64f4?utm_medium=terpyq&utm_source=weixinqun&from=timeline). It says `juejin hot fe`. Tried and it worked. But `juejin -h` says otherwise.

From what `juejin -h` says. I believe I'm using it the expected way. But the actual behavior tells me otherwise. One of them should change so the document matches the actual behavior. It's so confusing right now.

**Comment by cheng2xin** [comment]
yeah, i'll fix it right now ,ths.
